#language: android
#jdk: oraclejdk8
#sudo: true
#os:
#- linux
#addons:
#  apt_packages:
#  - pandoc
#  - cmake-data
#  - cmake
#  - ninja
#before_install:
#- mkdir -p $ANDROID_HOME/licenses
#- echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > $ANDROID_HOME/licenses/android-sdk-license
#- echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> $ANDROID_HOME/licenses/android-sdk-license
#install:
#- echo y | sdkmanager "ndk-bundle"
#- echo y | sdkmanager "cmake;3.6.4111459"
#- echo y | sdkmanager "lldb;3.1"
#android:
#  components:
#  - tools
#  - platform-tools
#  - tools
#  - build-tools-26.0.0
#  - android-26
#  licenses:
#  - android-sdk-preview-license-.+
#  - android-sdk-license-.+
#  - google-gdk-license-.+
script:
#- printenv | grep DROID
#- "/usr/bin/cmake --version"
- chmod +x gradlew
- "./gradlew --info check"
deploy:
  provider: releases
  api_key:
    secure: fob0cGOcb2dBMuiifopgo52MZDGQ8OOnRWoAO243UhFx73sMyaMkTB6gy76YiiT8gJhTzmyEtYlTE6YkwFpD1bBy0JCw6tZw7tUmvVQRM3jvCayDkJfHEObMm6ehQVgEgwL4C8/p9d8jMOolED7drm3/GzXd+8oJMDCd4eRb1WcxOGUYRiRFOsC/SVxwqIL9g488CQCT2nM8m+iqpnJ+cAqfRdOoO3AVW+iOsY2ygroctHyJlrhX/Q3KWPateKSy/LgW7dJ4pfJyJksMs+2Ve1/Dn/QrL4+dq0ygbJamQ3woWR1n1AyNpqKAxV5TkjXnQjnmHOy9EoEvs1iZmBMin+aYoMoZs7qn3FksAFy6Y7NomBwa/aRvbhl3ewFL4q5GLplOc6ZEjfaUFVHI8GoHJhlNkb+wp727d98WbiXUr00WosjS3xM//SIEGkwSlnoy0BAJ+aCkC+O4dUKiLwaKmvp70k67j5H6winEKguQ28mnW9NM/56wu2umiicFGNWenXgpJtKF4P7TS7qD06tzvmi9CI6E5DVZ/QuJESbnYOCFyPjtSqCZFey4yTPojC4dacd4BQhe0X4fA2JwbXPwoG3RGyerSLzY73yuuziDXIJaUnpb8k+6wzzAKGMuM4PE4I+YOJdLRGBQH8+0w03YRQTWSRMgf1Luh4YrtmqdRa0=
  file:
  - build/libs/toolprovision-${TRAVIS_TAG}.jar
  - build/libs/toolprovision-${TRAVIS_TAG}-sources.jar
  - build/libs/toolprovision-${TRAVIS_TAG}-javadoc.jar
  skip_cleanup: true
  on:
    tags: true
